# Generated by Django 5.1.7 on 2025-04-05 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_producttag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttag',
            name='products',
            field=models.ManyToManyField(blank=True, to='products.product'),
        ),
    ]
